import localFont from "next/font/local";
import "./globals.css";
import Achievements from "./component/Achievements";
import Service from "./component/Service";
import Work from "./component/Work";
import Footer from "./component/Footer";
import PricePage from "./component/PricePage";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Achievements/>
        <Service/>
        <PricePage/>
        <Work/>
        <Footer/>
      </body>
    </html>
  );
}
